# Generated by Django 3.2.6 on 2021-08-14 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rolls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rolls',
            new_name='Roll',
        ),
    ]
